cxxopts
RobertIndie/smark pull request #24
Opened 2020-06-21 11:47 UTC by Victor-wwj

诸如“thread_count”这样的变量在使用cxxopts库的时候第一次出现，所以我在前面先声明。
但是，这个应该是用户输入的，不应该第一次出现报错呀。。
或者我库的用法不对。

2020-06-21 12:55 UTC, RobertIndie requested changes
请麻烦解决相应的问题。

2020-06-21 12:55 UTC, RobertIndie commented on standalone/source/main.cpp
> +  int connection_count,thread_count;
这里不要使用 simple_http_port 作为端口参数变量名，建议使用port，并使用uint16_t类型。
相关的变量建议都与Smark类的相应成员变量类型对应上，比如connection_count和thread_count建议使用uint32_t类型

2020-06-21 12:55 UTC, RobertIndie commented on standalone/source/main.cpp
> +    ("c,connection","set the number of connection",cxxopts::value<int>(connection_count))
建议为这些参数都设置默认值：
ip默认值可为127.0.0.1，端口为80，threads和connections为1

2020-06-21 12:55 UTC, RobertIndie commented on standalone/source/main.cpp
需要添加异常处理，当用户以非法形式调用调用程序时，能够输出合理的错误提示信息。
最后还需要调用Smark类以运行程序。

2020-06-21 12:55 UTC, RobertIndie commented on standalone/source/main.cpp
>      ("l,lang", "Language code to use", cxxopts::value(language)->default_value("en"))
请将原来的用于示范如何使用cxxopts功能的测试代码移除，包括相关的功能和函数、main函数上的languages、Smark的_name成员以及greet函数

2020-06-21 13:31 UTC, Victor-wwj commented on standalone/source/main.cpp
> +    ("c,connection","set the number of connection",cxxopts::value<int>(connection_count))
直接初始化吗

2020-06-21 14:18 UTC, RobertIndie commented on standalone/source/main.cpp
> +    ("c,connection","set the number of connection",cxxopts::value<int>(connection_count))
> 直接初始化吗

不是，是像上面两行代码一样用default_value进行设置。

2020-06-21 14:24 UTC, RobertIndie commented
这个PR没有通过codecov，原因是没有和主仓库的master分支进行同步，可使用git rebase解决这个问题。
```shell
git remote add mainrepo git@github.com:RobertIndie/smark # 添加主仓库的remote，后续进行rebase时不需要用这个命令
git rebase mainrepo master # 在当前分支下进行rebase
```
对于Style不通过的问题，应该使用clang-format进行代码规范化。在REMEADE.MD的Run clang-format部分有介绍：
```shell
cmake --build build/test --target fix-format # 使用此命令进行代码规范化
```

2020-07-04 12:32 UTC, RobertIndie requested changes
对于Standalone的CI不通过问题：因为在CI的过程中没有运行相应的测试服务器，所以无法运行smark。为此，我建议CI的Standalone只进行编译检查。建议将`.github/workflows/standalone.yml`内的[run step](https://github.com/RobertIndie/smark/blob/master/.github/workflows/standalone.yml#L28-L29)给移除。
另外解决下CI的其他问题，以及以下review提出的问题。

2020-07-04 12:32 UTC, RobertIndie commented on standalone/source/main.cpp
>  const std::unordered_map<std::string, smark::LanguageCode> languages{
请将原来的用于示范如何使用cxxopts功能的测试代码移除，包括相关的功能和函数、main函数上的languages、Smark的_name成员以及greet函数

2020-07-04 12:32 UTC, RobertIndie commented on standalone/source/main.cpp
> +    catch(cxxopts::OptionParseException & miss1){
建议不要使用miss1作为此变量名，无法表明含义，可使用e、ex或者exception

2020-07-04 12:32 UTC, RobertIndie commented on standalone/source/main.cpp
> +//smark参数初始化及其调用
建议使用英文进行注释

2020-07-04 15:38 UTC, RobertIndie requested changes
请解决以下的问题

2020-07-04 15:38 UTC, RobertIndie commented on standalone/source/main.cpp
> -  // clang-format on
不要删除这里的`// clang-format on`，否则下面的代码都不会进行规范性检查。

2020-07-05 02:06 UTC, RobertIndie requested changes
> 请将原来的用于示范如何使用cxxopts功能的测试代码移除，包括相关的功能和函数、main函数上的languages、Smark的_name成员以及greet函数

还剩下Smark的_name成员以及greet函数，它们在source文件夹和include文件夹中。

2020-07-05 02:06 UTC, RobertIndie commented on standalone/source/main.cpp
> -    ("h,help", "Show help")
不要删掉help选项，否则无法输出help信息

2020-07-05 02:06 UTC, RobertIndie commented on standalone/source/main.cpp
> -  // clang-format on
这里仍然不起作用，你的`//`后缺少一个空格，应该是`// clang-format on`，这导致下面的代码都没法进行代码规范性检查。

2020-07-05 02:06 UTC, RobertIndie commented on standalone/source/main.cpp
> +    catch(cxxopts::OptionSpecException & ex2){
不要使用`ex1`、`ex2`的命名方式，建议使用`ex`，它们不属于同一个作用域，所以命名不会冲突。

2020-07-05 06:34 UTC, RobertIndie requested changes

2020-07-05 06:34 UTC, RobertIndie commented on standalone/source/main.cpp
> +    ("ip","set remote ip",cxxopts::value<std::string>(ip)->default_value("127.0.0.1"))
根据 #15 里的要求

> h, host: set remote host
p, port: set remote port
t, threads: set the number of threads.
c, connections: set the number of connections.

这里的ip应该是host，简写为h

2020-07-05 08:31 UTC, merged